# Generated by Django 3.0.6 on 2020-06-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clone.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profilepics/'),
        ),
    ]
