# Generated by Django 3.0.6 on 2020-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
