# Generated by Django 3.0.6 on 2020-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_auto_20200608_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='projectimages/'),
        ),
    ]
